"""Modular, Persian-aware associative and 4-tier persistent memory package."""

from __future__ import annotations

from dream.memory.context_files import (
    AGENTS_CAPACITY_CHARS,
    DEFAULT_CAPACITIES,
    DEFAULT_TEMPLATES,
    MEMORY_CAPACITY_CHARS,
    SOUL_CAPACITY_CHARS,
    USER_CAPACITY_CHARS,
    ContextCapacityError,
    ContextFileManager,
)
from dream.memory.models import (
    _MISSING,
    KINDS,
    CapacityReport,
    ContextFile,
    Memory,
    UserPersona,
)
from dream.memory.normalization import (
    _CANONICAL_MAP,
    _CHAR_MAP,
    _DIACRITICS,
    _DIGIT_MAP,
    _EXCLUDED_FROM_DUPLICATE_CANONICALISATION,
    _MIN_CONTRADICTION_PREFIX_TOKENS,
    _SUFFIXES,
    _SYNONYM_GROUPS,
    _SYNONYM_INDEX,
    _TOKEN_RE,
    _WS_RE,
    _ZWNJ,
    DEFAULT_CONTRADICTION_THRESHOLD,
    DEFAULT_DUPLICATE_THRESHOLD,
    _build_canonical_map,
    _build_synonym_index,
    _canonicalise_stems,
    _fts_escape,
    _is_contradiction,
    _is_duplicate,
    _load_extra_synonym_groups,
    _longest_common_subsequence,
    _resolve_contradiction_threshold,
    _resolve_duplicate_threshold,
    _stem_fa,
    _stemmed_tokens,
    _tokenize,
    build_match_query,
    normalize_fa,
)
from dream.memory.store import (
    _SCHEMA,
    HALF_LIFE_SECONDS,
    W_IMPORTANCE,
    W_RECENCY,
    W_RELEVANCE,
    W_USAGE,
    MemoryStore,
)
from dream.memory.user_modeling import DialecticalUserTracker

__all__ = [
    "AGENTS_CAPACITY_CHARS",
    "CapacityReport",
    "ContextCapacityError",
    "ContextFile",
    "ContextFileManager",
    "DEFAULT_CAPACITIES",
    "DEFAULT_CONTRADICTION_THRESHOLD",
    "DEFAULT_DUPLICATE_THRESHOLD",
    "DEFAULT_TEMPLATES",
    "DialecticalUserTracker",
    "HALF_LIFE_SECONDS",
    "KINDS",
    "MEMORY_CAPACITY_CHARS",
    "Memory",
    "MemoryStore",
    "SOUL_CAPACITY_CHARS",
    "USER_CAPACITY_CHARS",
    "UserPersona",
    "W_IMPORTANCE",
    "W_RECENCY",
    "W_RELEVANCE",
    "W_USAGE",
    "_CANONICAL_MAP",
    "_CHAR_MAP",
    "_DIACRITICS",
    "_DIGIT_MAP",
    "_EXCLUDED_FROM_DUPLICATE_CANONICALISATION",
    "_MIN_CONTRADICTION_PREFIX_TOKENS",
    "_MISSING",
    "_SCHEMA",
    "_SUFFIXES",
    "_SYNONYM_GROUPS",
    "_SYNONYM_INDEX",
    "_TOKEN_RE",
    "_WS_RE",
    "_ZWNJ",
    "_build_canonical_map",
    "_build_synonym_index",
    "_canonicalise_stems",
    "_fts_escape",
    "_is_contradiction",
    "_is_duplicate",
    "_load_extra_synonym_groups",
    "_longest_common_subsequence",
    "_resolve_contradiction_threshold",
    "_resolve_duplicate_threshold",
    "_stem_fa",
    "_stemmed_tokens",
    "_tokenize",
    "build_match_query",
    "normalize_fa",
]
