"""Pin commit authorship, trailer, and AI reference enforcement rules.

Evidence justifying this test:
- Rule 2 (authorship): Thirty commits on trunk were attributed to an automated
  account because authorship was never checked.
- Rule 3 (trailers): Forty-seven commits on trunk carried forbidden
  Co-authored-by trailers.
This module verifies that the checking logic in tools.check_commit correctly
rejects invalid authors, co-author trailers, and AI tooling references, while
passing on valid Ali Naderi commits.
"""

from tools.check_commit import (
    EXPECTED_AUTHOR_EMAIL,
    EXPECTED_AUTHOR_NAME,
    check_commit_author,
    check_commit_message,
)


def test_commit_author_valid():
    """An author matching Ali Naderi and the expected noreply email passes."""
    errors = check_commit_author(EXPECTED_AUTHOR_NAME, EXPECTED_AUTHOR_EMAIL)
    assert errors == []


def test_commit_author_invalid_name():
    """An automated account or unexpected author name is rejected."""
    errors = check_commit_author("automated-bot", EXPECTED_AUTHOR_EMAIL)
    assert len(errors) == 1
    assert "Invalid commit author name" in errors[0]


def test_commit_author_invalid_email():
    """An unexpected author email is rejected."""
    errors = check_commit_author(EXPECTED_AUTHOR_NAME, "someone@example.com")
    assert len(errors) == 1
    assert "Invalid commit author email" in errors[0]


def test_commit_message_valid():
    """A clean commit message with no co-author trailer or AI reference passes."""
    message = "M16: enforce commit rules and build checks (#32)"
    errors = check_commit_message(message)
    assert errors == []


def test_commit_message_rejects_co_authored_by_trailer():
    """A commit message with a Co-authored-by trailer is rejected."""
    message = (
        "M16: add check\n\n"
        "Co-authored-by: Another User <user@example.com>\n"
    )
    errors = check_commit_message(message)
    assert any("banned 'Co-authored-by:' trailer" in err for err in errors)


def test_commit_message_rejects_ai_tooling_reference():
    """A commit message referencing an AI agent or tool is rejected."""
    message = "M16: generated by ai with arena assistance"
    errors = check_commit_message(message)
    assert any("banned AI tooling reference" in err for err in errors)
