"""Hierarchical Multi-Subagent system for isolated, coordinated execution."""

from __future__ import annotations

from dream.subagents.constants import (
    DEFAULT_GRACE_SECONDS,
    DEFAULT_MAX_DURATION,
    DEFAULT_MAX_TOKENS,
    DEFAULT_MAX_TURNS,
    DEFAULT_TOOL_GRANT,
    MAX_CONTEXT_CHARS,
    MAX_DURATION_CAP,
    MAX_LOG_ENTRIES,
    MAX_LOG_MESSAGE_CHARS,
    MAX_NAME_CHARS,
    MAX_PIPELINE_STAGES,
    MAX_PROMPT_CHARS,
    MAX_RETAINED_SUBAGENTS,
    MAX_SYSTEM_PROMPT_CHARS,
    MAX_TOKENS_CAP,
    MAX_TOOL_GRANTS,
    MAX_TOOL_NAME_CHARS,
    MAX_TURNS_CAP,
    REGISTRY_LOCK,
    SUBAGENT_STATUSES,
    TERMINAL_STATUSES,
    estimate_tokens,
)
from dream.subagents.coordinator import BUILTIN_ROLES, SubagentCoordinator, SubagentRole
from dream.subagents.isolation import _build_backend, build_child_tools
from dream.subagents.manager import SubAgentManager
from dream.subagents.types import (
    LogEntry,
    SubAgent,
    SubAgentSpec,
    SubAgentStatus,
    subagent_to_dict,
)

__all__ = [
    "BUILTIN_ROLES",
    "DEFAULT_GRACE_SECONDS",
    "DEFAULT_MAX_DURATION",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_MAX_TURNS",
    "DEFAULT_TOOL_GRANT",
    "LogEntry",
    "MAX_CONTEXT_CHARS",
    "MAX_DURATION_CAP",
    "MAX_LOG_ENTRIES",
    "MAX_LOG_MESSAGE_CHARS",
    "MAX_NAME_CHARS",
    "MAX_PIPELINE_STAGES",
    "MAX_PROMPT_CHARS",
    "MAX_RETAINED_SUBAGENTS",
    "MAX_SYSTEM_PROMPT_CHARS",
    "MAX_TOKENS_CAP",
    "MAX_TOOL_GRANTS",
    "MAX_TOOL_NAME_CHARS",
    "MAX_TURNS_CAP",
    "REGISTRY_LOCK",
    "SUBAGENT_STATUSES",
    "SubAgent",
    "SubAgentManager",
    "SubAgentRole",
    "SubAgentSpec",
    "SubAgentStatus",
    "SubagentCoordinator",
    "SubagentRole",
    "TERMINAL_STATUSES",
    "_build_backend",
    "build_child_tools",
    "estimate_tokens",
    "subagent_to_dict",
]
