"""Commit authorship, trailer, and AI reference enforcement.

Checks that the HEAD commit (or specified commit SHA) obeys project
conventions:
1. Author name must be Ali Naderi.
2. Author email must be alinaderi@users.noreply.github.com.
3. No Co-authored-by trailer in the commit message.
4. No reference to any AI agent or AI tooling in the commit message.
"""

import re
import subprocess
import sys

EXPECTED_AUTHOR_NAME = "Ali Naderi"
EXPECTED_AUTHOR_EMAIL = "alinaderi@users.noreply.github.com"

# Substrings or regex patterns that indicate banned trailers or AI references.
BANNED_TRAILER_PATTERN = re.compile(r"^\s*Co-authored-by:.*", re.IGNORECASE | re.MULTILINE)
AI_TOOLING_WORDS = [
    "arena",
    "claude",
    "chatgpt",
    "openai",
    "gemini",
    "grok",
    "qwen",
    "kimi",
    "copilot",
    "anthropic",
    "llm",
    "ai-authored",
    "generated by ai",
    "assisted by ai",
]


def check_commit_author(author_name: str, author_email: str) -> list[str]:
    """Check author name and email against project conventions."""
    errors = []
    if author_name.strip() != EXPECTED_AUTHOR_NAME:
        errors.append(
            f"Invalid commit author name: {author_name!r}. Expected {EXPECTED_AUTHOR_NAME!r}."
        )
    if author_email.strip() != EXPECTED_AUTHOR_EMAIL:
        errors.append(
            f"Invalid commit author email: {author_email!r}. Expected {EXPECTED_AUTHOR_EMAIL!r}."
        )
    return errors


def check_commit_message(message: str) -> list[str]:
    """Check commit message for banned trailers and AI tooling references."""
    errors = []
    if BANNED_TRAILER_PATTERN.search(message):
        errors.append("Commit message contains banned 'Co-authored-by:' trailer.")

    msg_lower = message.lower()
    for word in AI_TOOLING_WORDS:
        # Check as a word boundary match where appropriate
        pattern = r"\b" + re.escape(word) + r"\b"
        if re.search(pattern, msg_lower):
            errors.append(f"Commit message contains banned AI tooling reference: {word!r}.")
    return errors


def get_commit_info(rev: str = "HEAD") -> tuple[str, str, str]:
    """Retrieve author name, author email, and full commit message for rev."""
    out = subprocess.check_output(
        ["git", "log", "-1", "--format=%an%x00%ae%x00%B", rev],
        text=True,
        encoding="utf-8",
    )
    parts = out.split("\x00", 2)
    if len(parts) != 3:
        raise ValueError(f"Unexpected git log format output: {out!r}")
    return parts[0].strip(), parts[1].strip(), parts[2]


def run_checks(rev: str = "HEAD") -> int:
    """Run authorship and message checks on rev."""
    try:
        author_name, author_email, message = get_commit_info(rev)
    except Exception as exc:
        print(f"ERROR: Could not retrieve git log for {rev}: {exc}", file=sys.stderr)
        return 1

    errors = check_commit_author(author_name, author_email)
    errors.extend(check_commit_message(message))

    if errors:
        print(f"Commit rule violations for {rev}:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    print(f"Commit author and trailer rules passed for {rev}!")
    return 0


def main() -> int:
    rev = sys.argv[1] if len(sys.argv) > 1 else "HEAD"
    return run_checks(rev)


if __name__ == "__main__":
    sys.exit(main())
