import { render, screen } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { describe, expect, it, vi } from 'vitest';

import { ArtifactDetailPanel } from './artifact-detail-panel';
import { ArtifactTreeView } from './artifact-tree-view';
import { ProvenanceTimeline } from './provenance-timeline';
import type { ArtifactDto, ProvenanceRecordDto, ProvenanceTreeDto } from '@/lib/bridge/types';

describe('Provenance UI Components', () => {
  const mockRecord: ProvenanceRecordDto = {
    record_id: 'prov_test_01',
    timestamp: '2026-08-15T12:00:00Z',
    event_type: 'tool_call',
    agent_id: 'sess_analysis',
    payload: { tool_name: 'generate_figure', arguments: { kind: 'bar' } },
    input_snapshot: [{ path: 'input.csv', hash: 'abc1234', size: 500, modified_at: 1700000000 }],
    output_snapshot: [{ path: 'chart.png', hash: 'def5678', size: 12000, modified_at: 1700000010 }],
    model_snapshot: { provider: 'openai', model: 'gpt-4o' },
    duration_ms: 150,
    token_count: 32,
    prev_hash: '0000000000000000',
    hash: 'sha256_mock_hash_test',
  };

  const mockArtifact: ArtifactDto = {
    artifact_path: 'reports/sales_chart.png',
    exists: true,
    size: 12000,
    hash: 'def567890abcdef',
    record_id: 'prov_test_01',
    tool_name: 'generate_figure',
    agent_id: 'sess_analysis',
    created_at: '2026-08-15T12:00:00Z',
    model: 'gpt-4o',
    lineage_statement:
      'This artifact was generated by generate_figure in session sess_analysis using model gpt-4o on 2026-08-15',
    generating_record: mockRecord,
  };

  const mockTree: ProvenanceTreeDto = {
    nodes: [
      {
        id: 'node_1',
        label: 'user_message: Plot sales',
        event_type: 'user_message',
        agent_id: 'sess_analysis',
        timestamp: '2026-08-15T11:59:00Z',
        payload: {},
        inputs: [],
        outputs: [],
      },
      {
        id: 'node_2',
        label: 'tool_call: generate_figure',
        event_type: 'tool_call',
        agent_id: 'sess_analysis',
        timestamp: '2026-08-15T12:00:00Z',
        duration_ms: 150,
        payload: { tool_name: 'generate_figure' },
        inputs: [{ path: 'input.csv', hash: 'abc1234', size: 500, modified_at: 1700000000 }],
        outputs: [{ path: 'chart.png', hash: 'def5678', size: 12000, modified_at: 1700000010 }],
      },
    ],
    edges: [{ source: 'node_1', target: 'node_2', type: 'parent_child' }],
    count: 2,
  };

  it('renders timeline with records and expands details on click', async () => {
    const onSelect = vi.fn();
    render(<ProvenanceTimeline records={[mockRecord]} onSelectRecord={onSelect} />);

    expect(screen.getByText(/Tool: generate_figure/i)).toBeInTheDocument();
    expect(screen.getByText('150ms')).toBeInTheDocument();

    // Click on row to trigger selection
    await userEvent.click(screen.getByText(/Tool: generate_figure/i));
    expect(onSelect).toHaveBeenCalledWith(mockRecord);
  });

  it('renders artifact tree view with DAG nodes', () => {
    const onSelectNode = vi.fn();
    render(<ArtifactTreeView tree={mockTree} onSelectNode={onSelectNode} />);

    expect(screen.getByText(/Artifact Lineage & Execution Tree/i)).toBeInTheDocument();
    expect(screen.getByText('user_message: Plot sales')).toBeInTheDocument();
    expect(screen.getByText('tool_call: generate_figure')).toBeInTheDocument();
  });

  it('renders artifact detail panel and triggers reproducibility export', async () => {
    const onExport = vi.fn();
    render(<ArtifactDetailPanel artifact={mockArtifact} onExportReproducibility={onExport} />);

    expect(screen.getByText('sales_chart.png')).toBeInTheDocument();
    expect(screen.getByText('generate_figure')).toBeInTheDocument();
    expect(screen.getByText(/Verified Artifact Lineage/i)).toBeInTheDocument();
    expect(screen.getByText(mockArtifact.lineage_statement)).toBeInTheDocument();

    const exportBtn = screen.getByRole('button', { name: /Export Reproducibility Zip/i });
    await userEvent.click(exportBtn);
    expect(onExport).toHaveBeenCalledWith('reports/sales_chart.png');
  });
});
